### PR TITLE
Add support for private repositories #4 

### PR DESCRIPTION
**Pull request by motiko**
Fix for issue #4 
### Configurations to make this work:
1. Add environment variable TOKEN_ENCRYPTION_KEY
2. Add Authorization callback URL to GitHub connected app https://githubsfdeploy.herokuapp.com/app/githubdeploy/authorizegh

### Implementation details
If the repository is not found and user is not authenticated to Github, user is redirected to Github authorize page. On callback encrypted cookie with access token is created.
On any later stage if access token cookie exist we authorize with it if authentication fails the cookie is revoked. 

### Few final points:
1. Did not tested with sandbox (although no problem is expected here)
2. Security can be enhanced 
  * Add secure random to state parameter 
  * Use stronger encryption
3. I'm planning to add support for webhooks and salesofrce test execution let me know what you think.

### CODE REVIEW

**Comment by afawcett** [comment]
Wow thanks so much for this! Can i ask what approach did you take to test it?

**Comment by motiko** [comment]
Deployed public repos to validate nothing is broken in old functionality. Deployed number of private repositories to salesforce. Tried revoking github access after view (confirm method) before deploy (error handling can be improved here). Generally looks fine.
 I'll be using it a lot next few weeks and make sure to fix and report if I find any bugs.

**Comment by afawcett** [comment]
Having found a way to remove whitespace from the diffs, reviewing this was a lot easier, it looks pretty good to be honest, nice work! I guess one improvement would be to use server side session state to store the GitHub oAuth token and thus would not need to worry about the encryption peace and env var. If thats not something your that familiar with that's cool though.

**Comment by motiko** [comment]
Good idea looks like @SessionAttributes can take care of that. Never used it in Spring but i guess i can digg into that. Probably be ready with a commit by next weekend.

**Comment by afawcett** [comment]
:+1:

**Comment by motiko** [comment]
I ended up using HttpSession, now there is no need for env var nor for encryption.
Sorry about the whitespace i replaced spaces back to tabs but still $ git diff (without -w) is pretty messy.
BTW how do you remove whitepace from Github diff ?

**Comment by afawcett** [comment]
Thanks @motiko looking good, sorry for the late reply, i've been on holiday, just got back.

To remove white space put ?w=1 on the end of the URL.

https://github.com/afawcett/githubsfdeploy/pull/6/files?w=1

So my next step is to merge this then update the Heroku apps.

This maybe easier said than done, keep GitHub and Heroku's repos in sync has always been a pain point for this tool in setting up the Eclipse setup, which since i've moved to a new Mac will need to be done again. I may take this chance to review the new GitHub and Heroku integration that has arrived recently.

Anyway, just to let you know i'm happy with the changes, and will try next weekend to update! Thank you again so much for this great peace of work, is do you have a Twitter handle btw, i'd like to tweet about this. Also maybe a blog post or short entry in the README file describing the support?

**Comment by motiko** [comment]
I was using your tools and learning from your blog for a long time now so thank you very much for this and it is my pleasure to give something back.
I've had a chance to use GitHub to Heroku deploy and its working fine and pretty simple to setup.
My twitter handler is @moti_kor but I don't have a blog so I've added a few lines in the README for now.

**Comment by afawcett** [comment]
Thats so kind, i'm glad you've really enjoyed my work so far and continue to do so!

I have now merged and deployed the changes, but i am getting an error.

screen shot 2015-05-23 at 09 49 23

**Comment by afawcett** [comment]
Ah i see i had to update the callback URL in my oAuth config. 

Since Sandbox works via a second hosted Heroku app (with different config) on a different domain hence URL, i'll probably need to create a second oAuth app to support that, since the callback URL will be different for sandbox. I think...

**Comment by afawcett** [comment]
Ok on to the next error it seems... 

screen shot 2015-05-23 at 10 07 21

**Comment by afawcett** [comment]
Here is the stack dump...

2015-05-23T09:07:51.512981+00:00 app[web.1]: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
2015-05-23T09:07:51.513591+00:00 app[web.1]: 	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740)
2015-05-23T09:07:51.513689+00:00 app[web.1]: 	at org.eclipse.egit.github.core.service.ContentsService.getContents(ContentsService.java:146)
2015-05-23T09:07:51.513725+00:00 app[web.1]: 	at org.eclipse.egit.github.core.service.ContentsService.getContents(ContentsService.java:109)
2015-05-23T09:07:51.513832+00:00 app[web.1]: 	at org.eclipse.egit.github.core.service.ContentsService.getContents(ContentsService.java:96)
2015-05-23T09:07:51.513856+00:00 app[web.1]: 	at com.andyinthecloud.githubsfdeploy.controller.GitHubSalesforceDeployController.confirm(GitHubSalesforceDeployController.java:200)
2015-05-23T09:07:51.513904+00:00 app[web.1]: 	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
2015-05-23T09:07:51.513925+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-05-23T09:07:51.513964+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:606)
2015-05-23T09:07:51.513994+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
2015-05-23T09:07:51.514025+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
2015-05-23T09:07:51.514048+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
2015-05-23T09:07:51.514092+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
2015-05-23T09:07:51.514135+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
2015-05-23T09:07:51.514156+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
2015-05-23T09:07:51.514176+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
2015-05-23T09:07:51.514217+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
2015-05-23T09:07:51.514253+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
2015-05-23T09:07:51.514273+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
2015-05-23T09:07:51.514313+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
2015-05-23T09:07:51.514342+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
2015-05-23T09:07:51.514373+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
2015-05-23T09:07:51.514412+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
2015-05-23T09:07:51.514435+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:343)
2015-05-23T09:07:51.514491+00:00 app[web.1]: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
2015-05-23T09:07:51.514512+00:00 app[web.1]: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
2015-05-23T09:07:51.514532+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514579+00:00 app[web.1]: 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:97)
2015-05-23T09:07:51.514610+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514631+00:00 app[web.1]: 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:100)
2015-05-23T09:07:51.514671+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514700+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:78)
2015-05-23T09:07:51.514733+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514798+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514847+00:00 app[web.1]: 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:112)
2015-05-23T09:07:51.514913+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.514774+00:00 app[web.1]: 	at com.force.sdk.springsecurity.ForceConnectionStorageFilter.doFilter(ForceConnectionStorageFilter.java:112)
2015-05-23T09:07:51.514963+00:00 app[web.1]: 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
2015-05-23T09:07:51.515027+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.515073+00:00 app[web.1]: 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:35)
2015-05-23T09:07:51.515094+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.515132+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:187)
2015-05-23T09:07:51.515175+00:00 app[web.1]: 	at com.force.sdk.springsecurity.AuthenticationProcessingFilter.doFilter(AuthenticationProcessingFilter.java:109)
2015-05-23T09:07:51.515205+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.515251+00:00 app[web.1]: 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
2015-05-23T09:07:51.515271+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.515305+00:00 app[web.1]: 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:79)
2015-05-23T09:07:51.515327+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
2015-05-23T09:07:51.515347+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:149)
2015-05-23T09:07:51.515385+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
2015-05-23T09:07:51.515431+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
2015-05-23T09:07:51.515452+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
2015-05-23T09:07:51.515490+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
2015-05-23T09:07:51.515519+00:00 app[web.1]: 	at com.andyinthecloud.githubsfdeploy.config.OAuthConfigChecker.doFilter(OAuthConfigChecker.java:19)
2015-05-23T09:07:51.515549+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
2015-05-23T09:07:51.515588+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
2015-05-23T09:07:51.515666+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
2015-05-23T09:07:51.515626+00:00 app[web.1]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
2015-05-23T09:07:51.515687+00:00 app[web.1]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
2015-05-23T09:07:51.515709+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
2015-05-23T09:07:51.515758+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
2015-05-23T09:07:51.515781+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
2015-05-23T09:07:51.515813+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)
2015-05-23T09:07:51.516455+00:00 app[web.1]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:964)
2015-05-23T09:07:51.516488+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)
2015-05-23T09:07:51.516507+00:00 app[web.1]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:302)
2015-05-23T09:07:51.516526+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-05-23T09:07:51.516544+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-05-23T09:07:51.516563+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by afawcett** [comment]
Ok user error, i typed in the wrong repo name....

Doing more testing now...

**Comment by afawcett** [comment]
Ok so..... it sorta works....i do find now and again i either get a popup with an error or large exception...but then when i try again it works... so it seems little unstable at the mo... Thankfully only when dealing with private repos. Can you try from your side and see what your experience is please...

**Comment by afawcett** [comment]
Ok i need to go do something else now, but one final observation... if i log out of salesforce and it has to go through the login process i seem to get the error more often. If i do repeated deploys (without closing my browser) after logging in it seems much more stable.

**Comment by motiko** [comment]
I will try to reproduce this tomorrow morning. Meanwhile if you have any more details please share with me.

**Comment by motiko** [comment]
Ok it seems like I've reconstructed the problem. 
The root of the problem ForceServiceConnector on the first deploy after authenticating to GitHub for some reason is not recognising that we are authenticated to salesforce and redirects to salesforce oauth page. I'm investigating this further right now and will update as soon as i find something.

**Comment by motiko** [comment]
To fix change to following line

    return "redirect:" + "https://github.com/login/oauth/authorize?client_id=" + System.getenv(GITHUB_CLIENT_ID) + "&scope=repo&state=" + request.getRequestURL().toString();

to 

    return "redirect:" + "https://github.com/login/oauth/authorize?client_id=" + System.getenv(GITHUB_CLIENT_ID) + "&scope=repo&state=" + request.getRequestURI();

The reason is state param is used for redirection after /authorizegh is saving github access token  and getRequestURI return only the path part (which is sufficient)  instead of the full URL (which resets the state).

**Comment by afawcett** [comment]
Awesome thats sorted it! Thanks again! :+1:

**Pull request merged**
