### PR TITLE
Better error handling after token revoked #10

### PR DESCRIPTION
**Pull request by motiko**
Now if token is revoked from salesforce, session is cleared on our side and user is redirected to authorize page.
Fixing issue #10

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks, does this address one of the open issues by any chance?

**Comment by motiko** [comment]
Yes it fixes issue #10 
I'm still looking for a way to address #9 basically all i need is an instance url

**Comment by afawcett** [comment]
OK cool, i've now updated the Heroku apps, can you give a quick retest please?

**Comment by motiko** [comment]
It works, after revoking token I'm sent to authorization page on second try to upload, there is still place for improvement (improving error handling and generally UX) but it is better that the situation it was where the user stuck with no way to recover. I'll push another PR next week with improvements and hopefully a fix for #9 .

**Comment by afawcett** [comment]
Very much appreciated, its not one of my strongest areas tbh and thus sorta stuff would take a me much longer then you i'm sure! :+1:

**Pull request merged**
